<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cb</string>
	</array>
	<key>name</key>
	<string>CodeBot</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^(define|group|bind|auton|math|raw)</string>
			<key>name</key>
			<string>entity.name.function.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(motor|channel|button|group|servo|sensor|loop|init)</string>
			<key>name</key>
			<string>keyword.control.flow.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([0-9|\.|\-][A-Z]|[0-9|\.|\-]|\$[a-zA-Z\_]+)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\!\*.*\*\!</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.python</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.python</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.line.number-sign.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(input|port|sensitivity|reversed|run|rest)</string>
			<key>name</key>
			<string>support.function.builtin.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([a-zA-Z\_]+)</string>
			<key>name</key>
			<string>meta.preprocessor.c</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>codebot.cb</string>
	<key>uuid</key>
	<string>c7e16b37-8c2d-4fc5-9c01-4bf0f5b803a9</string>
</dict>
</plist>
